plugins {
    id 'com.android.application'
    id 'com.android.legacy-kapt'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace 'ru.uxfeedback.demoapplication'
    compileSdk 37
    defaultConfig {
        applicationId "ru.uxfeedback.demoapplication"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildFeatures {
        buildConfig true
        dataBinding true
        viewBinding true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.18.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"
    implementation "com.github.skydoves:colorpickerview:2.2.4"
    implementation 'ru.uxfeedback:sdk:4.4.0'
    implementation "com.google.dagger:hilt-android:2.59.2"
    kapt "com.google.dagger:hilt-compiler:2.59.2"
    implementation "com.google.code.gson:gson:2.9.1"
    implementation 'joda-time:joda-time:2.10.10'

}